### ISSUE TITLE
Failed to liquidate account: Returned error: The execution failed due to an exception

### ISSUE THREAD

**Issue by gonchs** [dydxprotocol/liquidator#10]
**Error:**

```
{
  "at": "SoloLiquidator#_liquidateAccounts",
  "message": "Failed to liquidate account: Returned error: The execution failed due to an exception.",
  "accountUuid": "00bdbb2c-b5a3-47d0-be36-700dc5454181",
  "accountOwner": "0x0d0a3e0031ec20c4ff31e5a7b67e1b183fd7343d",
  "accountNumber": "76888185948525730161192672454758448786428429970077845206929115285875975152786",
  "error": {
    "transactionData": {
      "from": "0xe9FA0A8ded2AffF8F867DfE820e52bC79cAC0c79",
      "data": "0xc29a4b71000000000000000000000000e9fa0a8ded2afff8f867dfe820e52bc79cac0c7900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d0a3e0031ec20c4ff31e5a7b67e1b183fd7343da9fd2bca5acd7dd0111310e809539d40131418db01f8fe317a6ab6d700c2649200000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000004a7ab4d9debdbd64563e8330000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002",
      "to": "0xD4B6cd147ad8A0D5376b6FDBa85fE8128C6f0686"
    }
  }
}
Error: Returned error: The execution failed due to an exception.
    at Object.ErrorResponse (/home/sergey/dydx-liquidator/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /home/sergey/dydx-liquidator/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/home/sergey/dydx-liquidator/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/sergey/dydx-liquidator/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/sergey/dydx-liquidator/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/sergey/dydx-liquidator/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/sergey/dydx-liquidator/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2019-07-16 16:24:01 [[31merror[39m]: {
  "at": "SoloLiquidator#_liquidateAccounts",
  "message": "Failed to liquidate account: Returned error: The execution failed due to an exception.",
  "accountUuid": "4b0edcb3-c277-4394-8917-a0cc9d5ecc9e",
  "accountOwner": "0x91f7fdd0cd1a8960f52dd739f40339830fbba0c9",
  "accountNumber": "71777313707452876206445525887268247350305604617912941782117165212786100847741",
  "error": {
    "transactionData": {
      "from": "0xe9FA0A8ded2AffF8F867DfE820e52bC79cAC0c79",
      "data": "0xc29a4b71000000000000000000000000e9fa0a8ded2afff8f867dfe820e52bc79cac0c79000000000000000000000000000000000000000000000000000000000000000000000000000000000000000091f7fdd0cd1a8960f52dd739f40339830fbba0c99eb08516d5c5af95c62c4f27c5d3a1432cd8e8017bc464641361db606e58c47d00000000000000000000000000000000000000000000000029a2241af62c0000000000000000000000000000000000004a7ab4d9debdbd64563e8330000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002",
      "to": "0xD4B6cd147ad8A0D5376b6FDBa85fE8128C6f0686"
    }
  }
}
```

**Config:**

```
DYDX_URL=https://api.dydx.exchange

GAS_STATION_URL=http://ethgasstation.info/json/ethgasAPI.json
GAS_PRICE_MULTIPLIER=2.1
GAS_PRICE_UPDATE_FREQUENCY_SEC=30
INITIAL_GAS_PRICE=30000000000
GAS_REQUEST_TIMEOUT_MS=10000

LIQUIDATION_KEY_EXPIRATION_SEC=240
LIQUIDATION_COLLATERAL_PREFERENCES=0,1,2
LIQUIDATION_OWED_PREFERENCES=0,1,2
MIN_LIQUIDATOR_ACCOUNT_COLLATERALIZATION=3
MIN_VALUE_LIQUIDATED=99e36
LIQUIDATOR_ACCOUNT_OWNER=hidden
LIQUIDATOR_ACCOUNT_OWNER_PRIVATE_KEY=hidden
EXPIRED_ACCOUNT_LIQUIDATION_DELAY_SECONDS=3000
ENABLE_EXPIRATIONS=true

LIQUIDATOR_ACCOUNT_NUMBER=0

ETHEREUM_NODE_URL=https://parity.expotrading.com
NETWORK_ID=1
ACCOUNT_POLL_INTERVAL_MS=2000
MARKET_POLL_INTERVAL_MS=2000
SOLO_LIQUIDATE_POLL_INTERVAL_MS=2000
```

**Comment by BrendanChou** [comment]
Probably the account was no-longer-liquidatable when attempting to run it through gas-estimation
