### ISSUE TITLE
Issue with the bot

### ISSUE THREAD

**Issue by saumyabratadutt** [dydxprotocol/liquidator#31]
Starting in env undefined
2020-04-28 09:09:56 [error]: {
  "at": "solo#loadAccounts",
  "message": "Owner private key does not match address",
  "expected": "0xb75eb924568D4eBf65d9Bb932C589c3c06a59655",
  "got": "0xb8d61d84354Ed34cf8eD89e751Dec3fc6Fc77cCD",
  "error": {}
}
Error: Owner private key does not match address
    at loadAccounts (/home/dydx/app/build/helpers/solo.js:29:14)
    at start (/home/dydx/app/build/index.js:38:32)
    at Object.<anonymous> (/home/dydx/app/build/index.js:45:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2020-04-28 09:09:57 [info]: {
  "at": "solo#loadAccounts",
  "message": "Liquidation proxy contract has not been approved. Approving...",
  "address": "0xb8d61d84354Ed34cf8eD89e751Dec3fc6Fc77cCD",
  "proxyAddress": "0xD4B6cd147ad8A0D5376b6FDBa85fE8128C6f0686"
}
(node:24) UnhandledPromiseRejectionWarning: Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/dydx/app/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /home/dydx/app/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/home/dydx/app/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/dydx/app/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/dydx/app/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/dydx/app/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/dydx/app/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by michaeldim** [comment]
See #27 that may be the issue.

**Comment by saumyabratadutt** [comment]
Thanks, that worked out!
What's the minimum amount of coins do I keep in the account for each cryptocurrency? Is there a group I can join?

**Comment by michaeldim** [comment]
You're probably better off asking those sort of questions in their [dYdX telegram group](https://t.me/joinchat/GBnMlBb9mQblQck2pThTgw).

**Comment by Huge** [comment]
> You're probably better off asking those sort of questions in their [dYdX telegram group](https://t.me/joinchat/GBnMlBb9mQblQck2pThTgw).

The link expired, I've tried multiple devices, where to get in touch with the team currently?
