### ISSUE TITLE
TypeError: Cannot read property 'fromRed' of null

### ISSUE THREAD

**Issue by leoplct** [dydxprotocol/liquidator#46]
I am running this on Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-77-generic x86_64) with latest docker installed

```
docker run \
  -e WALLET_ADDRESS=0xXXXXXXXX \
  -e WALLET_PRIVATE_KEY=XXXXXXXXXX \
  -e ETHEREUM_NODE_URL=https://mainnet.infura.io/v3/XXXXXXX \
  -e SOLO_LIQUIDATIONS_ENABLED=true \
  -e SOLO_EXPIRATIONS_ENABLED=false \
  dydxprotocol/liquidator
```

but I got this error

```
> liquidator@2.1.1 start /home/dydx/app
> node build/index.js

Starting in env undefined
(node:25) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fromRed' of null
    at Point.getX (/home/dydx/app/node_modules/elliptic/lib/elliptic/curve/short.js:415:17)
    at Point._encode (/home/dydx/app/node_modules/elliptic/lib/elliptic/curve/base.js:295:16)
    at Point.encode (/home/dydx/app/node_modules/elliptic/lib/elliptic/curve/base.js:304:28)
    at KeyPair.getPublic (/home/dydx/app/node_modules/elliptic/lib/elliptic/ec/key.js:66:19)
    at Object.fromPrivate (/home/dydx/app/node_modules/eth-lib/lib/account.js:31:32)
    at Accounts.privateKeyToAccount (/home/dydx/app/node_modules/web3-eth-accounts/src/index.js:129:46)
    at Wallet.add (/home/dydx/app/node_modules/web3-eth-accounts/src/index.js:429:34)
    at loadAccounts (/home/dydx/app/build/helpers/web3.js:48:53)
    at start (/home/dydx/app/build/index.js:41:31)
    at Object.<anonymous> (/home/dydx/app/build/index.js:60:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by leoplct** [comment]
It was missing 0x at the starts of WALLET_PRIVATE_KEY
