### ISSUE TITLE
i have error running the bot

### ISSUE THREAD

**Issue by kayden111** [dydxprotocol/liquidator#47]
> liquidator@2.1.1 start /home/dydx/app
> node build/index.js

Starting in env undefined
2021-10-10 13:04:51 [info]: {
  "at": "web3#loadAccounts",
  "message": "Loaded liquidator account",
  "address": "*****************************"
}
(node:25) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/dydx/app/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/home/dydx/app/node_modules/web3-providers-http/src/index.js:92:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/dydx/app/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/dydx/app/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/home/dydx/app/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/home/dydx/app/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by michaeldim** [comment]
I wouldn't waste your time trying to resolve this issue as the bot is pretty much obsolete - https://dydx.exchange/blog/layer-1-wind-down

**Comment by kayden111** [comment]
What do you recommend? Go to other platform and build a bot ?

**Comment by michaeldim** [comment]
> Any bot work for layer 2? 
I think dydx run Liquidations internally on l2

**Comment by kayden111** [comment]
Manually sending contract is not an option because people are using bot that are faster
